<?php
/**
 * File containing the ExtensionMimeTypeGuesser class part of the BcDocumentReaderBundle package.
 * Based on the Symfony\Component\HttpFoundation\File\MimeType\MimeTypeGuesserInterface class provided by Symfony.
 * Extended and based upon uniquely to find matching file extension from the content of the $defaultExtensions and $customMimeTypeExtensions class variables and return the matching file extension's mimetype.
 *
 * @copyright Copyright (C) Brookins Consulting. All rights reserved.
 * @copyright Copyright (C) Fabien Potencier <fabien@symfony.com>
 * @license For full copyright and license information view LICENSE and COPYRIGHT.md file distributed with this source code.
 * @version //autogentag//
 */

namespace BrookinsConsulting\BcDocumentReaderBundle\Symfony\Component\HttpFoundation\File\MimeType;

use Symfony\Component\HttpFoundation\File\MimeType\ExtensionGuesserInterface;
use Symfony\Component\HttpFoundation\File\MimeType\MimeTypeExtensionGuesser;

/**
 * Provides a best-guess mapping of mime type to file extension.
 */
class ExtensionMimeTypeGuesser extends MimeTypeExtensionGuesser implements ExtensionGuesserInterface
{
    /**
     * A map of mime types and their default extensions.
     *
     * This list has been placed under the public domain by the Apache HTTPD project.
     * This list has been updated from upstream on 2013-04-23.
     *
     * @see http://svn.apache.org/repos/asf/httpd/httpd/trunk/docs/conf/mime.types
     *
     * @var array
     */
    protected $defaultExtensions = array(
        array( 'application/andrew-inset' => 'ez' ),
        array( 'application/applixware' => 'aw' ),
        array( 'application/atom+xml' => 'atom' ),
        array( 'application/atomcat+xml' => 'atomcat' ),
        array( 'application/atomsvc+xml' => 'atomsvc' ),
        array( 'application/ccxml+xml' => 'ccxml' ),
        array( 'application/cdmi-capability' => 'cdmia' ),
        array( 'application/cdmi-container' => 'cdmic' ),
        array( 'application/cdmi-domain' => 'cdmid' ),
        array( 'application/cdmi-object' => 'cdmio' ),
        array( 'application/cdmi-queue' => 'cdmiq' ),
        array( 'application/cu-seeme' => 'cu' ),
        array( 'application/davmount+xml' => 'davmount' ),
        array( 'application/docbook+xml' => 'dbk' ),
        array( 'application/dssc+der' => 'dssc' ),
        array( 'application/dssc+xml' => 'xdssc' ),
        array( 'application/ecmascript' => 'ecma' ),
        array( 'application/emma+xml' => 'emma' ),
        array( 'application/epub+zip' => 'epub' ),
        array( 'application/exi' => 'exi' ),
        array( 'application/font-tdpfr' => 'pfr' ),
        array( 'application/gml+xml' => 'gml' ),
        array( 'application/gpx+xml' => 'gpx' ),
        array( 'application/gxf' => 'gxf' ),
        array( 'application/hyperstudio' => 'stk' ),
        array( 'application/inkml+xml' => 'ink' ),
        array( 'application/ipfix' => 'ipfix' ),
        array( 'application/java-archive' => 'jar' ),
        array( 'application/java-serialized-object' => 'ser' ),
        array( 'application/java-vm' => 'class' ),
        array( 'application/javascript' => 'js' ),
        array( 'application/json' => 'json' ),
        array( 'application/jsonml+json' => 'jsonml' ),
        array( 'application/lost+xml' => 'lostxml' ),
        array( 'application/mac-binhex40' => 'hqx' ),
        array( 'application/mac-compactpro' => 'cpt' ),
        array( 'application/mads+xml' => 'mads' ),
        array( 'application/marc' => 'mrc' ),
        array( 'application/marcxml+xml' => 'mrcx' ),
        array( 'application/mathematica' => 'ma' ),
        array( 'application/mathml+xml' => 'mathml' ),
        array( 'application/mbox' => 'mbox' ),
        array( 'application/mediaservercontrol+xml' => 'mscml' ),
        array( 'application/metalink+xml' => 'metalink' ),
        array( 'application/metalink4+xml' => 'meta4' ),
        array( 'application/mets+xml' => 'mets' ),
        array( 'application/mods+xml' => 'mods' ),
        array( 'application/mp21' => 'm21' ),
        array( 'application/mp4' => 'mp4s' ),
        array( 'application/msword' => 'doc' ),
        array( 'application/mxf' => 'mxf' ),
        array( 'application/octet-stream' => 'bin' ),
        array( 'application/oda' => 'oda' ),
        array( 'application/oebps-package+xml' => 'opf' ),
        array( 'application/ogg' => 'ogx' ),
        array( 'application/omdoc+xml' => 'omdoc' ),
        array( 'application/onenote' => 'onetoc' ),
        array( 'application/oxps' => 'oxps' ),
        array( 'application/patch-ops-error+xml' => 'xer' ),
        array( 'application/pdf' => 'pdf' ),
        array( 'application/pgp-encrypted' => 'pgp' ),
        array( 'application/pgp-signature' => 'asc' ),
        array( 'application/pics-rules' => 'prf' ),
        array( 'application/pkcs10' => 'p10' ),
        array( 'application/pkcs7-mime' => 'p7m' ),
        array( 'application/pkcs7-signature' => 'p7s' ),
        array( 'application/pkcs8' => 'p8' ),
        array( 'application/pkix-attr-cert' => 'ac' ),
        array( 'application/pkix-cert' => 'cer' ),
        array( 'application/pkix-crl' => 'crl' ),
        array( 'application/pkix-pkipath' => 'pkipath' ),
        array( 'application/pkixcmp' => 'pki' ),
        array( 'application/pls+xml' => 'pls' ),
        array( 'application/postscript' => 'ai' ),
        array( 'application/prs.cww' => 'cww' ),
        array( 'application/pskc+xml' => 'pskcxml' ),
        array( 'application/rdf+xml' => 'rdf' ),
        array( 'application/reginfo+xml' => 'rif' ),
        array( 'application/relax-ng-compact-syntax' => 'rnc' ),
        array( 'application/resource-lists+xml' => 'rl' ),
        array( 'application/resource-lists-diff+xml' => 'rld' ),
        array( 'application/rls-services+xml' => 'rs' ),
        array( 'application/rpki-ghostbusters' => 'gbr' ),
        array( 'application/rpki-manifest' => 'mft' ),
        array( 'application/rpki-roa' => 'roa' ),
        array( 'application/rsd+xml' => 'rsd' ),
        array( 'application/rss+xml' => 'rss' ),
        array( 'application/rtf' => 'rtf' ),
        array( 'application/sbml+xml' => 'sbml' ),
        array( 'application/scvp-cv-request' => 'scq' ),
        array( 'application/scvp-cv-response' => 'scs' ),
        array( 'application/scvp-vp-request' => 'spq' ),
        array( 'application/scvp-vp-response' => 'spp' ),
        array( 'application/sdp' => 'sdp' ),
        array( 'application/set-payment-initiation' => 'setpay' ),
        array( 'application/set-registration-initiation' => 'setreg' ),
        array( 'application/shf+xml' => 'shf' ),
        array( 'application/smil+xml' => 'smi' ),
        array( 'application/sparql-query' => 'rq' ),
        array( 'application/sparql-results+xml' => 'srx' ),
        array( 'application/srgs' => 'gram' ),
        array( 'application/srgs+xml' => 'grxml' ),
        array( 'application/sru+xml' => 'sru' ),
        array( 'application/ssdl+xml' => 'ssdl' ),
        array( 'application/ssml+xml' => 'ssml' ),
        array( 'application/tei+xml' => 'tei' ),
        array( 'application/thraud+xml' => 'tfi' ),
        array( 'application/timestamped-data' => 'tsd' ),
        array( 'application/vnd.3gpp.pic-bw-large' => 'plb' ),
        array( 'application/vnd.3gpp.pic-bw-small' => 'psb' ),
        array( 'application/vnd.3gpp.pic-bw-var' => 'pvb' ),
        array( 'application/vnd.3gpp2.tcap' => 'tcap' ),
        array( 'application/vnd.3m.post-it-notes' => 'pwn' ),
        array( 'application/vnd.accpac.simply.aso' => 'aso' ),
        array( 'application/vnd.accpac.simply.imp' => 'imp' ),
        array( 'application/vnd.acucobol' => 'acu' ),
        array( 'application/vnd.acucorp' => 'atc' ),
        array( 'application/vnd.adobe.air-application-installer-package+zip' => 'air' ),
        array( 'application/vnd.adobe.formscentral.fcdt' => 'fcdt' ),
        array( 'application/vnd.adobe.fxp' => 'fxp' ),
        array( 'application/vnd.adobe.xdp+xml' => 'xdp' ),
        array( 'application/vnd.adobe.xfdf' => 'xfdf' ),
        array( 'application/vnd.ahead.space' => 'ahead' ),
        array( 'application/vnd.airzip.filesecure.azf' => 'azf' ),
        array( 'application/vnd.airzip.filesecure.azs' => 'azs' ),
        array( 'application/vnd.amazon.ebook' => 'azw' ),
        array( 'application/vnd.americandynamics.acc' => 'acc' ),
        array( 'application/vnd.amiga.ami' => 'ami' ),
        array( 'application/vnd.android.package-archive' => 'apk' ),
        array( 'application/vnd.anser-web-certificate-issue-initiation' => 'cii' ),
        array( 'application/vnd.anser-web-funds-transfer-initiation' => 'fti' ),
        array( 'application/vnd.antix.game-component' => 'atx' ),
        array( 'application/vnd.apple.installer+xml' => 'mpkg' ),
        array( 'application/vnd.apple.mpegurl' => 'm3u8' ),
        array( 'application/vnd.aristanetworks.swi' => 'swi' ),
        array( 'application/vnd.astraea-software.iota' => 'iota' ),
        array( 'application/vnd.audiograph' => 'aep' ),
        array( 'application/vnd.blueice.multipass' => 'mpm' ),
        array( 'application/vnd.bmi' => 'bmi' ),
        array( 'application/vnd.businessobjects' => 'rep' ),
        array( 'application/vnd.chemdraw+xml' => 'cdxml' ),
        array( 'application/vnd.chipnuts.karaoke-mmd' => 'mmd' ),
        array( 'application/vnd.cinderella' => 'cdy' ),
        array( 'application/vnd.claymore' => 'cla' ),
        array( 'application/vnd.cloanto.rp9' => 'rp9' ),
        array( 'application/vnd.clonk.c4group' => 'c4g' ),
        array( 'application/vnd.cluetrust.cartomobile-config' => 'c11amc' ),
        array( 'application/vnd.cluetrust.cartomobile-config-pkg' => 'c11amz' ),
        array( 'application/vnd.commonspace' => 'csp' ),
        array( 'application/vnd.contact.cmsg' => 'cdbcmsg' ),
        array( 'application/vnd.cosmocaller' => 'cmc' ),
        array( 'application/vnd.crick.clicker' => 'clkx' ),
        array( 'application/vnd.crick.clicker.keyboard' => 'clkk' ),
        array( 'application/vnd.crick.clicker.palette' => 'clkp' ),
        array( 'application/vnd.crick.clicker.template' => 'clkt' ),
        array( 'application/vnd.crick.clicker.wordbank' => 'clkw' ),
        array( 'application/vnd.criticaltools.wbs+xml' => 'wbs' ),
        array( 'application/vnd.ctc-posml' => 'pml' ),
        array( 'application/vnd.cups-ppd' => 'ppd' ),
        array( 'application/vnd.curl.car' => 'car' ),
        array( 'application/vnd.curl.pcurl' => 'pcurl' ),
        array( 'application/vnd.dart' => 'dart' ),
        array( 'application/vnd.data-vision.rdz' => 'rdz' ),
        array( 'application/vnd.dece.data' => 'uvf' ),
        array( 'application/vnd.dece.ttml+xml' => 'uvt' ),
        array( 'application/vnd.dece.unspecified' => 'uvx' ),
        array( 'application/vnd.dece.zip' => 'uvz' ),
        array( 'application/vnd.denovo.fcselayout-link' => 'fe_launch' ),
        array( 'application/vnd.dna' => 'dna' ),
        array( 'application/vnd.dolby.mlp' => 'mlp' ),
        array( 'application/vnd.dpgraph' => 'dpg' ),
        array( 'application/vnd.dreamfactory' => 'dfac' ),
        array( 'application/vnd.ds-keypoint' => 'kpxx' ),
        array( 'application/vnd.dvb.ait' => 'ait' ),
        array( 'application/vnd.dvb.service' => 'svc' ),
        array( 'application/vnd.dynageo' => 'geo' ),
        array( 'application/vnd.ecowin.chart' => 'mag' ),
        array( 'application/vnd.enliven' => 'nml' ),
        array( 'application/vnd.epson.esf' => 'esf' ),
        array( 'application/vnd.epson.msf' => 'msf' ),
        array( 'application/vnd.epson.quickanime' => 'qam' ),
        array( 'application/vnd.epson.salt' => 'slt' ),
        array( 'application/vnd.epson.ssf' => 'ssf' ),
        array( 'application/vnd.eszigno3+xml' => 'es3' ),
        array( 'application/vnd.ezpix-album' => 'ez2' ),
        array( 'application/vnd.ezpix-package' => 'ez3' ),
        array( 'application/vnd.fdf' => 'fdf' ),
        array( 'application/vnd.fdsn.mseed' => 'mseed' ),
        array( 'application/vnd.fdsn.seed' => 'seed' ),
        array( 'application/vnd.flographit' => 'gph' ),
        array( 'application/vnd.fluxtime.clip' => 'ftc' ),
        array( 'application/vnd.framemaker' => 'fm' ),
        array( 'application/vnd.frogans.fnc' => 'fnc' ),
        array( 'application/vnd.frogans.ltf' => 'ltf' ),
        array( 'application/vnd.fsc.weblaunch' => 'fsc' ),
        array( 'application/vnd.fujitsu.oasys' => 'oas' ),
        array( 'application/vnd.fujitsu.oasys2' => 'oa2' ),
        array( 'application/vnd.fujitsu.oasys3' => 'oa3' ),
        array( 'application/vnd.fujitsu.oasysgp' => 'fg5' ),
        array( 'application/vnd.fujitsu.oasysprs' => 'bh2' ),
        array( 'application/vnd.fujixerox.ddd' => 'ddd' ),
        array( 'application/vnd.fujixerox.docuworks' => 'xdw' ),
        array( 'application/vnd.fujixerox.docuworks.binder' => 'xbd' ),
        array( 'application/vnd.fuzzysheet' => 'fzs' ),
        array( 'application/vnd.genomatix.tuxedo' => 'txd' ),
        array( 'application/vnd.geogebra.file' => 'ggb' ),
        array( 'application/vnd.geogebra.tool' => 'ggt' ),
        array( 'application/vnd.geometry-explorer' => 'gex' ),
        array( 'application/vnd.geonext' => 'gxt' ),
        array( 'application/vnd.geoplan' => 'g2w' ),
        array( 'application/vnd.geospace' => 'g3w' ),
        array( 'application/vnd.gmx' => 'gmx' ),
        array( 'application/vnd.google-earth.kml+xml' => 'kml' ),
        array( 'application/vnd.google-earth.kmz' => 'kmz' ),
        array( 'application/vnd.grafeq' => 'gqf' ),
        array( 'application/vnd.groove-account' => 'gac' ),
        array( 'application/vnd.groove-help' => 'ghf' ),
        array( 'application/vnd.groove-identity-message' => 'gim' ),
        array( 'application/vnd.groove-injector' => 'grv' ),
        array( 'application/vnd.groove-tool-message' => 'gtm' ),
        array( 'application/vnd.groove-tool-template' => 'tpl' ),
        array( 'application/vnd.groove-vcard' => 'vcg' ),
        array( 'application/vnd.hal+xml' => 'hal' ),
        array( 'application/vnd.handheld-entertainment+xml' => 'zmm' ),
        array( 'application/vnd.hbci' => 'hbci' ),
        array( 'application/vnd.hhe.lesson-player' => 'les' ),
        array( 'application/vnd.hp-hpgl' => 'hpgl' ),
        array( 'application/vnd.hp-hpid' => 'hpid' ),
        array( 'application/vnd.hp-hps' => 'hps' ),
        array( 'application/vnd.hp-jlyt' => 'jlt' ),
        array( 'application/vnd.hp-pcl' => 'pcl' ),
        array( 'application/vnd.hp-pclxl' => 'pclxl' ),
        array( 'application/vnd.hydrostatix.sof-data' => 'sfd-hdstx' ),
        array( 'application/vnd.ibm.minipay' => 'mpy' ),
        array( 'application/vnd.ibm.modcap' => 'afp' ),
        array( 'application/vnd.ibm.rights-management' => 'irm' ),
        array( 'application/vnd.ibm.secure-container' => 'sc' ),
        array( 'application/vnd.iccprofile' => 'icc' ),
        array( 'application/vnd.igloader' => 'igl' ),
        array( 'application/vnd.immervision-ivp' => 'ivp' ),
        array( 'application/vnd.immervision-ivu' => 'ivu' ),
        array( 'application/vnd.insors.igm' => 'igm' ),
        array( 'application/vnd.intercon.formnet' => 'xpw' ),
        array( 'application/vnd.intergeo' => 'i2g' ),
        array( 'application/vnd.intu.qbo' => 'qbo' ),
        array( 'application/vnd.intu.qfx' => 'qfx' ),
        array( 'application/vnd.ipunplugged.rcprofile' => 'rcprofile' ),
        array( 'application/vnd.irepository.package+xml' => 'irp' ),
        array( 'application/vnd.is-xpr' => 'xpr' ),
        array( 'application/vnd.isac.fcs' => 'fcs' ),
        array( 'application/vnd.jam' => 'jam' ),
        array( 'application/vnd.jcp.javame.midlet-rms' => 'rms' ),
        array( 'application/vnd.jisp' => 'jisp' ),
        array( 'application/vnd.joost.joda-archive' => 'joda' ),
        array( 'application/vnd.kahootz' => 'ktz' ),
        array( 'application/vnd.kde.karbon' => 'karbon' ),
        array( 'application/vnd.kde.kchart' => 'chrt' ),
        array( 'application/vnd.kde.kformula' => 'kfo' ),
        array( 'application/vnd.kde.kivio' => 'flw' ),
        array( 'application/vnd.kde.kontour' => 'kon' ),
        array( 'application/vnd.kde.kpresenter' => 'kpr' ),
        array( 'application/vnd.kde.kspread' => 'ksp' ),
        array( 'application/vnd.kde.kword' => 'kwd' ),
        array( 'application/vnd.kenameaapp' => 'htke' ),
        array( 'application/vnd.kidspiration' => 'kia' ),
        array( 'application/vnd.kinar' => 'kne' ),
        array( 'application/vnd.koan' => 'skp' ),
        array( 'application/vnd.kodak-descriptor' => 'sse' ),
        array( 'application/vnd.las.las+xml' => 'lasxml' ),
        array( 'application/vnd.llamagraphics.life-balance.desktop' => 'lbd' ),
        array( 'application/vnd.llamagraphics.life-balance.exchange+xml' => 'lbe' ),
        array( 'application/vnd.lotus-1-2-3' => '123' ),
        array( 'application/vnd.lotus-approach' => 'apr' ),
        array( 'application/vnd.lotus-freelance' => 'pre' ),
        array( 'application/vnd.lotus-notes' => 'nsf' ),
        array( 'application/vnd.lotus-organizer' => 'org' ),
        array( 'application/vnd.lotus-screencam' => 'scm' ),
        array( 'application/vnd.lotus-wordpro' => 'lwp' ),
        array( 'application/vnd.macports.portpkg' => 'portpkg' ),
        array( 'application/vnd.mcd' => 'mcd' ),
        array( 'application/vnd.medcalcdata' => 'mc1' ),
        array( 'application/vnd.mediastation.cdkey' => 'cdkey' ),
        array( 'application/vnd.mfer' => 'mwf' ),
        array( 'application/vnd.mfmp' => 'mfm' ),
        array( 'application/vnd.micrografx.flo' => 'flo' ),
        array( 'application/vnd.micrografx.igx' => 'igx' ),
        array( 'application/vnd.mif' => 'mif' ),
        array( 'application/vnd.mobius.daf' => 'daf' ),
        array( 'application/vnd.mobius.dis' => 'dis' ),
        array( 'application/vnd.mobius.mbk' => 'mbk' ),
        array( 'application/vnd.mobius.mqy' => 'mqy' ),
        array( 'application/vnd.mobius.msl' => 'msl' ),
        array( 'application/vnd.mobius.plc' => 'plc' ),
        array( 'application/vnd.mobius.txf' => 'txf' ),
        array( 'application/vnd.mophun.application' => 'mpn' ),
        array( 'application/vnd.mophun.certificate' => 'mpc' ),
        array( 'application/vnd.mozilla.xul+xml' => 'xul' ),
        array( 'application/vnd.ms-artgalry' => 'cil' ),
        array( 'application/vnd.ms-cab-compressed' => 'cab' ),
        array( 'application/vnd.ms-excel' => 'xls' ),
        array( 'application/vnd.ms-excel.addin.macroenabled.12' => 'xlam' ),
        array( 'application/vnd.ms-excel.sheet.binary.macroenabled.12' => 'xlsb' ),
        array( 'application/vnd.ms-excel.sheet.macroenabled.12' => 'xlsm' ),
        array( 'application/vnd.ms-excel.template.macroenabled.12' => 'xltm' ),
        array( 'application/vnd.ms-fontobject' => 'eot' ),
        array( 'application/vnd.ms-htmlhelp' => 'chm' ),
        array( 'application/vnd.ms-ims' => 'ims' ),
        array( 'application/vnd.ms-lrm' => 'lrm' ),
        array( 'application/vnd.ms-officetheme' => 'thmx' ),
        array( 'application/vnd.ms-pki.seccat' => 'cat' ),
        array( 'application/vnd.ms-pki.stl' => 'stl' ),
        array( 'application/vnd.ms-powerpoint' => 'ppt' ),
        array( 'application/vnd.ms-powerpoint.addin.macroenabled.12' => 'ppam' ),
        array( 'application/vnd.ms-powerpoint.presentation.macroenabled.12' => 'pptm' ),
        array( 'application/vnd.ms-powerpoint.slide.macroenabled.12' => 'sldm' ),
        array( 'application/vnd.ms-powerpoint.slideshow.macroenabled.12' => 'ppsm' ),
        array( 'application/vnd.ms-powerpoint.template.macroenabled.12' => 'potm' ),
        array( 'application/vnd.ms-project' => 'mpp' ),
        array( 'application/vnd.ms-word.document.macroenabled.12' => 'docm' ),
        array( 'application/vnd.ms-word.template.macroenabled.12' => 'dotm' ),
        array( 'application/vnd.ms-works' => 'wps' ),
        array( 'application/vnd.ms-wpl' => 'wpl' ),
        array( 'application/vnd.ms-xpsdocument' => 'xps' ),
        array( 'application/vnd.mseq' => 'mseq' ),
        array( 'application/vnd.musician' => 'mus' ),
        array( 'application/vnd.muvee.style' => 'msty' ),
        array( 'application/vnd.mynfc' => 'taglet' ),
        array( 'application/vnd.neurolanguage.nlu' => 'nlu' ),
        array( 'application/vnd.nitf' => 'ntf' ),
        array( 'application/vnd.noblenet-directory' => 'nnd' ),
        array( 'application/vnd.noblenet-sealer' => 'nns' ),
        array( 'application/vnd.noblenet-web' => 'nnw' ),
        array( 'application/vnd.nokia.n-gage.data' => 'ngdat' ),
        array( 'application/vnd.nokia.n-gage.symbian.install' => 'n-gage' ),
        array( 'application/vnd.nokia.radio-preset' => 'rpst' ),
        array( 'application/vnd.nokia.radio-presets' => 'rpss' ),
        array( 'application/vnd.novadigm.edm' => 'edm' ),
        array( 'application/vnd.novadigm.edx' => 'edx' ),
        array( 'application/vnd.novadigm.ext' => 'ext' ),
        array( 'application/vnd.oasis.opendocument.chart' => 'odc' ),
        array( 'application/vnd.oasis.opendocument.chart-template' => 'otc' ),
        array( 'application/vnd.oasis.opendocument.database' => 'odb' ),
        array( 'application/vnd.oasis.opendocument.formula' => 'odf' ),
        array( 'application/vnd.oasis.opendocument.formula-template' => 'odft' ),
        array( 'application/vnd.oasis.opendocument.graphics' => 'odg' ),
        array( 'application/vnd.oasis.opendocument.graphics-template' => 'otg' ),
        array( 'application/vnd.oasis.opendocument.image' => 'odi' ),
        array( 'application/vnd.oasis.opendocument.image-template' => 'oti' ),
        array( 'application/vnd.oasis.opendocument.presentation' => 'odp' ),
        array( 'application/vnd.oasis.opendocument.presentation-template' => 'otp' ),
        array( 'application/vnd.oasis.opendocument.spreadsheet' => 'ods' ),
        array( 'application/vnd.oasis.opendocument.spreadsheet-template' => 'ots' ),
        array( 'application/vnd.oasis.opendocument.text' => 'odt' ),
        array( 'application/vnd.oasis.opendocument.text-master' => 'odm' ),
        array( 'application/vnd.oasis.opendocument.text-template' => 'ott' ),
        array( 'application/vnd.oasis.opendocument.text-web' => 'oth' ),
        array( 'application/vnd.olpc-sugar' => 'xo' ),
        array( 'application/vnd.oma.dd2+xml' => 'dd2' ),
        array( 'application/vnd.openofficeorg.extension' => 'oxt' ),
        array( 'application/vnd.openxmlformats-officedocument.presentationml.presentation' => 'pptx' ),
        array( 'application/vnd.openxmlformats-officedocument.presentationml.slide' => 'sldx' ),
        array( 'application/vnd.openxmlformats-officedocument.presentationml.slideshow' => 'ppsx' ),
        array( 'application/vnd.openxmlformats-officedocument.presentationml.template' => 'potx' ),
        array( 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' => 'xlsx' ),
        array( 'application/vnd.openxmlformats-officedocument.spreadsheetml.template' => 'xltx' ),
        array( 'application/vnd.openxmlformats-officedocument.wordprocessingml.document' => 'docx' ),
        array( 'application/vnd.openxmlformats-officedocument.wordprocessingml.template' => 'dotx' ),
        array( 'application/vnd.osgeo.mapguide.package' => 'mgp' ),
        array( 'application/vnd.osgi.dp' => 'dp' ),
        array( 'application/vnd.osgi.subsystem' => 'esa' ),
        array( 'application/vnd.palm' => 'pdb' ),
        array( 'application/vnd.pawaafile' => 'paw' ),
        array( 'application/vnd.pg.format' => 'str' ),
        array( 'application/vnd.pg.osasli' => 'ei6' ),
        array( 'application/vnd.picsel' => 'efif' ),
        array( 'application/vnd.pmi.widget' => 'wg' ),
        array( 'application/vnd.pocketlearn' => 'plf' ),
        array( 'application/vnd.powerbuilder6' => 'pbd' ),
        array( 'application/vnd.previewsystems.box' => 'box' ),
        array( 'application/vnd.proteus.magazine' => 'mgz' ),
        array( 'application/vnd.publishare-delta-tree' => 'qps' ),
        array( 'application/vnd.pvi.ptid1' => 'ptid' ),
        array( 'application/vnd.quark.quarkxpress' => 'qxd' ),
        array( 'application/vnd.realvnc.bed' => 'bed' ),
        array( 'application/vnd.recordare.musicxml' => 'mxl' ),
        array( 'application/vnd.recordare.musicxml+xml' => 'musicxml' ),
        array( 'application/vnd.rig.cryptonote' => 'cryptonote' ),
        array( 'application/vnd.rim.cod' => 'cod' ),
        array( 'application/vnd.rn-realmedia' => 'rm' ),
        array( 'application/vnd.rn-realmedia-vbr' => 'rmvb' ),
        array( 'application/vnd.route66.link66+xml' => 'link66' ),
        array( 'application/vnd.sailingtracker.track' => 'st' ),
        array( 'application/vnd.seemail' => 'see' ),
        array( 'application/vnd.sema' => 'sema' ),
        array( 'application/vnd.semd' => 'semd' ),
        array( 'application/vnd.semf' => 'semf' ),
        array( 'application/vnd.shana.informed.formdata' => 'ifm' ),
        array( 'application/vnd.shana.informed.formtemplate' => 'itp' ),
        array( 'application/vnd.shana.informed.interchange' => 'iif' ),
        array( 'application/vnd.shana.informed.package' => 'ipk' ),
        array( 'application/vnd.simtech-mindmapper' => 'twd' ),
        array( 'application/vnd.smaf' => 'mmf' ),
        array( 'application/vnd.smart.teacher' => 'teacher' ),
        array( 'application/vnd.solent.sdkm+xml' => 'sdkm' ),
        array( 'application/vnd.spotfire.dxp' => 'dxp' ),
        array( 'application/vnd.spotfire.sfs' => 'sfs' ),
        array( 'application/vnd.stardivision.calc' => 'sdc' ),
        array( 'application/vnd.stardivision.draw' => 'sda' ),
        array( 'application/vnd.stardivision.impress' => 'sdd' ),
        array( 'application/vnd.stardivision.math' => 'smf' ),
        array( 'application/vnd.stardivision.writer' => 'sdw' ),
        array( 'application/vnd.stardivision.writer-global' => 'sgl' ),
        array( 'application/vnd.stepmania.package' => 'smzip' ),
        array( 'application/vnd.stepmania.stepchart' => 'sm' ),
        array( 'application/vnd.sun.xml.calc' => 'sxc' ),
        array( 'application/vnd.sun.xml.calc.template' => 'stc' ),
        array( 'application/vnd.sun.xml.draw' => 'sxd' ),
        array( 'application/vnd.sun.xml.draw.template' => 'std' ),
        array( 'application/vnd.sun.xml.impress' => 'sxi' ),
        array( 'application/vnd.sun.xml.impress.template' => 'sti' ),
        array( 'application/vnd.sun.xml.math' => 'sxm' ),
        array( 'application/vnd.sun.xml.writer' => 'sxw' ),
        array( 'application/vnd.sun.xml.writer.global' => 'sxg' ),
        array( 'application/vnd.sun.xml.writer.template' => 'stw' ),
        array( 'application/vnd.sus-calendar' => 'sus' ),
        array( 'application/vnd.svd' => 'svd' ),
        array( 'application/vnd.symbian.install' => 'sis' ),
        array( 'application/vnd.syncml+xml' => 'xsm' ),
        array( 'application/vnd.syncml.dm+wbxml' => 'bdm' ),
        array( 'application/vnd.syncml.dm+xml' => 'xdm' ),
        array( 'application/vnd.tao.intent-module-archive' => 'tao' ),
        array( 'application/vnd.tcpdump.pcap' => 'pcap' ),
        array( 'application/vnd.tmobile-livetv' => 'tmo' ),
        array( 'application/vnd.trid.tpt' => 'tpt' ),
        array( 'application/vnd.triscape.mxs' => 'mxs' ),
        array( 'application/vnd.trueapp' => 'tra' ),
        array( 'application/vnd.ufdl' => 'ufd' ),
        array( 'application/vnd.uiq.theme' => 'utz' ),
        array( 'application/vnd.umajin' => 'umj' ),
        array( 'application/vnd.unity' => 'unityweb' ),
        array( 'application/vnd.uoml+xml' => 'uoml' ),
        array( 'application/vnd.vcx' => 'vcx' ),
        array( 'application/vnd.visio' => 'vsd' ),
        array( 'application/vnd.visionary' => 'vis' ),
        array( 'application/vnd.vsf' => 'vsf' ),
        array( 'application/vnd.wap.wbxml' => 'wbxml' ),
        array( 'application/vnd.wap.wmlc' => 'wmlc' ),
        array( 'application/vnd.wap.wmlscriptc' => 'wmlsc' ),
        array( 'application/vnd.webturbo' => 'wtb' ),
        array( 'application/vnd.wolfram.player' => 'nbp' ),
        array( 'application/vnd.wordperfect' => 'wpd' ),
        array( 'application/vnd.wqd' => 'wqd' ),
        array( 'application/vnd.wt.stf' => 'stf' ),
        array( 'application/vnd.xara' => 'xar' ),
        array( 'application/vnd.xfdl' => 'xfdl' ),
        array( 'application/vnd.yamaha.hv-dic' => 'hvd' ),
        array( 'application/vnd.yamaha.hv-script' => 'hvs' ),
        array( 'application/vnd.yamaha.hv-voice' => 'hvp' ),
        array( 'application/vnd.yamaha.openscoreformat' => 'osf' ),
        array( 'application/vnd.yamaha.openscoreformat.osfpvg+xml' => 'osfpvg' ),
        array( 'application/vnd.yamaha.smaf-audio' => 'saf' ),
        array( 'application/vnd.yamaha.smaf-phrase' => 'spf' ),
        array( 'application/vnd.yellowriver-custom-menu' => 'cmp' ),
        array( 'application/vnd.zul' => 'zir' ),
        array( 'application/vnd.zzazz.deck+xml' => 'zaz' ),
        array( 'application/voicexml+xml' => 'vxml' ),
        array( 'application/widget' => 'wgt' ),
        array( 'application/winhlp' => 'hlp' ),
        array( 'application/wsdl+xml' => 'wsdl' ),
        array( 'application/wspolicy+xml' => 'wspolicy' ),
        array( 'application/x-7z-compressed' => '7z' ),
        array( 'application/x-abiword' => 'abw' ),
        array( 'application/x-ace-compressed' => 'ace' ),
        array( 'application/x-apple-diskimage' => 'dmg' ),
        array( 'application/x-authorware-bin' => 'aab' ),
        array( 'application/x-authorware-map' => 'aam' ),
        array( 'application/x-authorware-seg' => 'aas' ),
        array( 'application/x-bcpio' => 'bcpio' ),
        array( 'application/x-bittorrent' => 'torrent' ),
        array( 'application/x-blorb' => 'blb' ),
        array( 'application/x-bzip' => 'bz' ),
        array( 'application/x-bzip2' => 'bz2' ),
        array( 'application/x-cbr' => 'cbr' ),
        array( 'application/x-cdlink' => 'vcd' ),
        array( 'application/x-cfs-compressed' => 'cfs' ),
        array( 'application/x-chat' => 'chat' ),
        array( 'application/x-chess-pgn' => 'pgn' ),
        array( 'application/x-conference' => 'nsc' ),
        array( 'application/x-cpio' => 'cpio' ),
        array( 'application/x-csh' => 'csh' ),
        array( 'application/x-debian-package' => 'deb' ),
        array( 'application/x-dgc-compressed' => 'dgc' ),
        array( 'application/x-director' => 'dir' ),
        array( 'application/x-doom' => 'wad' ),
        array( 'application/x-dtbncx+xml' => 'ncx' ),
        array( 'application/x-dtbook+xml' => 'dtb' ),
        array( 'application/x-dtbresource+xml' => 'res' ),
        array( 'application/x-dvi' => 'dvi' ),
        array( 'application/x-envoy' => 'evy' ),
        array( 'application/x-eva' => 'eva' ),
        array( 'application/x-font-bdf' => 'bdf' ),
        array( 'application/x-font-ghostscript' => 'gsf' ),
        array( 'application/x-font-linux-psf' => 'psf' ),
        array( 'application/x-font-otf' => 'otf' ),
        array( 'application/x-font-pcf' => 'pcf' ),
        array( 'application/x-font-snf' => 'snf' ),
        array( 'application/x-font-ttf' => 'ttf' ),
        array( 'application/x-font-type1' => 'pfa' ),
        array( 'application/x-font-woff' => 'woff' ),
        array( 'application/x-freearc' => 'arc' ),
        array( 'application/x-futuresplash' => 'spl' ),
        array( 'application/x-gca-compressed' => 'gca' ),
        array( 'application/x-glulx' => 'ulx' ),
        array( 'application/x-gnumeric' => 'gnumeric' ),
        array( 'application/x-gramps-xml' => 'gramps' ),
        array( 'application/x-gtar' => 'gtar' ),
        array( 'application/x-hdf' => 'hdf' ),
        array( 'application/x-install-instructions' => 'install' ),
        array( 'application/x-iso9660-image' => 'iso' ),
        array( 'application/x-java-jnlp-file' => 'jnlp' ),
        array( 'application/x-latex' => 'latex' ),
        array( 'application/x-lzh-compressed' => 'lzh' ),
        array( 'application/x-mie' => 'mie' ),
        array( 'application/x-mobipocket-ebook' => 'prc' ),
        array( 'application/x-ms-application' => 'application' ),
        array( 'application/x-ms-shortcut' => 'lnk' ),
        array( 'application/x-ms-wmd' => 'wmd' ),
        array( 'application/x-ms-wmz' => 'wmz' ),
        array( 'application/x-ms-xbap' => 'xbap' ),
        array( 'application/x-msaccess' => 'mdb' ),
        array( 'application/x-msbinder' => 'obd' ),
        array( 'application/x-mscardfile' => 'crd' ),
        array( 'application/x-msclip' => 'clp' ),
        array( 'application/x-msdownload' => 'exe' ),
        array( 'application/x-msmediaview' => 'mvb' ),
        array( 'application/x-msmetafile' => 'wmf' ),
        array( 'application/x-msmoney' => 'mny' ),
        array( 'application/x-mspublisher' => 'pub' ),
        array( 'application/x-msschedule' => 'scd' ),
        array( 'application/x-msterminal' => 'trm' ),
        array( 'application/x-mswrite' => 'wri' ),
        array( 'application/x-netcdf' => 'nc' ),
        array( 'application/x-nzb' => 'nzb' ),
        array( 'application/x-pkcs12' => 'p12' ),
        array( 'application/x-pkcs7-certificates' => 'p7b' ),
        array( 'application/x-pkcs7-certreqresp' => 'p7r' ),
        array( 'application/x-rar-compressed' => 'rar' ),
        array( 'application/x-rar' => 'rar' ),
        array( 'application/x-research-info-systems' => 'ris' ),
        array( 'application/x-sh' => 'sh' ),
        array( 'application/x-shar' => 'shar' ),
        array( 'application/x-shockwave-flash' => 'swf' ),
        array( 'application/x-silverlight-app' => 'xap' ),
        array( 'application/x-sql' => 'sql' ),
        array( 'application/x-stuffit' => 'sit' ),
        array( 'application/x-stuffitx' => 'sitx' ),
        array( 'application/x-subrip' => 'srt' ),
        array( 'application/x-sv4cpio' => 'sv4cpio' ),
        array( 'application/x-sv4crc' => 'sv4crc' ),
        array( 'application/x-t3vm-image' => 't3' ),
        array( 'application/x-tads' => 'gam' ),
        array( 'application/x-tar' => 'tar' ),
        array( 'application/x-tcl' => 'tcl' ),
        array( 'application/x-tex' => 'tex' ),
        array( 'application/x-tex-tfm' => 'tfm' ),
        array( 'application/x-texinfo' => 'texinfo' ),
        array( 'application/x-tgif' => 'obj' ),
        array( 'application/x-ustar' => 'ustar' ),
        array( 'application/x-wais-source' => 'src' ),
        array( 'application/x-x509-ca-cert' => 'der' ),
        array( 'application/x-xfig' => 'fig' ),
        array( 'application/x-xliff+xml' => 'xlf' ),
        array( 'application/x-xpinstall' => 'xpi' ),
        array( 'application/x-xz' => 'xz' ),
        array( 'application/x-zmachine' => 'z1' ),
        array( 'application/xaml+xml' => 'xaml' ),
        array( 'application/xcap-diff+xml' => 'xdf' ),
        array( 'application/xenc+xml' => 'xenc' ),
        array( 'application/xhtml+xml' => 'xhtml' ),
        array( 'application/xml' => 'xml' ),
        array( 'application/xml-dtd' => 'dtd' ),
        array( 'application/xop+xml' => 'xop' ),
        array( 'application/xproc+xml' => 'xpl' ),
        array( 'application/xslt+xml' => 'xslt' ),
        array( 'application/xspf+xml' => 'xspf' ),
        array( 'application/xv+xml' => 'mxml' ),
        array( 'application/yang' => 'yang' ),
        array( 'application/yin+xml' => 'yin' ),
        array( 'application/zip' => 'zip' ),
        array( 'audio/adpcm' => 'adp' ),
        array( 'audio/basic' => 'au' ),
        array( 'audio/midi' => 'mid' ),
        array( 'audio/mp4' => 'mp4a' ),
        array( 'audio/mpeg' => 'mpga' ),
        array( 'audio/ogg' => 'oga' ),
        array( 'audio/s3m' => 's3m' ),
        array( 'audio/silk' => 'sil' ),
        array( 'audio/vnd.dece.audio' => 'uva' ),
        array( 'audio/vnd.digital-winds' => 'eol' ),
        array( 'audio/vnd.dra' => 'dra' ),
        array( 'audio/vnd.dts' => 'dts' ),
        array( 'audio/vnd.dts.hd' => 'dtshd' ),
        array( 'audio/vnd.lucent.voice' => 'lvp' ),
        array( 'audio/vnd.ms-playready.media.pya' => 'pya' ),
        array( 'audio/vnd.nuera.ecelp4800' => 'ecelp4800' ),
        array( 'audio/vnd.nuera.ecelp7470' => 'ecelp7470' ),
        array( 'audio/vnd.nuera.ecelp9600' => 'ecelp9600' ),
        array( 'audio/vnd.rip' => 'rip' ),
        array( 'audio/webm' => 'weba' ),
        array( 'audio/x-aac' => 'aac' ),
        array( 'audio/x-aiff' => 'aif' ),
        array( 'audio/x-caf' => 'caf' ),
        array( 'audio/x-flac' => 'flac' ),
        array( 'audio/x-matroska' => 'mka' ),
        array( 'audio/x-mpegurl' => 'm3u' ),
        array( 'audio/x-ms-wax' => 'wax' ),
        array( 'audio/x-ms-wma' => 'wma' ),
        array( 'audio/x-pn-realaudio' => 'ram' ),
        array( 'audio/x-pn-realaudio-plugin' => 'rmp' ),
        array( 'audio/x-wav' => 'wav' ),
        array( 'audio/xm' => 'xm' ),
        array( 'chemical/x-cdx' => 'cdx' ),
        array( 'chemical/x-cif' => 'cif' ),
        array( 'chemical/x-cmdf' => 'cmdf' ),
        array( 'chemical/x-cml' => 'cml' ),
        array( 'chemical/x-csml' => 'csml' ),
        array( 'chemical/x-xyz' => 'xyz' ),
        array( 'image/bmp' => 'bmp' ),
        array( 'image/x-ms-bmp' => 'bmp' ),
        array( 'image/cgm' => 'cgm' ),
        array( 'image/g3fax' => 'g3' ),
        array( 'image/gif' => 'gif' ),
        array( 'image/ief' => 'ief' ),
        array( 'image/jpeg' => 'jpeg' ),
        array( 'image/ktx' => 'ktx' ),
        array( 'image/png' => 'png' ),
        array( 'image/prs.btif' => 'btif' ),
        array( 'image/sgi' => 'sgi' ),
        array( 'image/svg+xml' => 'svg' ),
        array( 'image/tiff' => 'tiff' ),
        array( 'image/vnd.adobe.photoshop' => 'psd' ),
        array( 'image/vnd.dece.graphic' => 'uvi' ),
        array( 'image/vnd.dvb.subtitle' => 'sub' ),
        array( 'image/vnd.djvu' => 'djvu' ),
        array( 'image/vnd.dwg' => 'dwg' ),
        array( 'image/vnd.dxf' => 'dxf' ),
        array( 'image/vnd.fastbidsheet' => 'fbs' ),
        array( 'image/vnd.fpx' => 'fpx' ),
        array( 'image/vnd.fst' => 'fst' ),
        array( 'image/vnd.fujixerox.edmics-mmr' => 'mmr' ),
        array( 'image/vnd.fujixerox.edmics-rlc' => 'rlc' ),
        array( 'image/vnd.ms-modi' => 'mdi' ),
        array( 'image/vnd.ms-photo' => 'wdp' ),
        array( 'image/vnd.net-fpx' => 'npx' ),
        array( 'image/vnd.wap.wbmp' => 'wbmp' ),
        array( 'image/vnd.xiff' => 'xif' ),
        array( 'image/webp' => 'webp' ),
        array( 'image/x-3ds' => '3ds' ),
        array( 'image/x-cmu-raster' => 'ras' ),
        array( 'image/x-cmx' => 'cmx' ),
        array( 'image/x-freehand' => 'fh' ),
        array( 'image/x-icon' => 'ico' ),
        array( 'image/x-mrsid-image' => 'sid' ),
        array( 'image/x-pcx' => 'pcx' ),
        array( 'image/x-pict' => 'pic' ),
        array( 'image/x-portable-anymap' => 'pnm' ),
        array( 'image/x-portable-bitmap' => 'pbm' ),
        array( 'image/x-portable-graymap' => 'pgm' ),
        array( 'image/x-portable-pixmap' => 'ppm' ),
        array( 'image/x-rgb' => 'rgb' ),
        array( 'image/x-tga' => 'tga' ),
        array( 'image/x-xbitmap' => 'xbm' ),
        array( 'image/x-xpixmap' => 'xpm' ),
        array( 'image/x-xwindowdump' => 'xwd' ),
        array( 'message/rfc822' => 'eml' ),
        array( 'model/iges' => 'igs' ),
        array( 'model/mesh' => 'msh' ),
        array( 'model/vnd.collada+xml' => 'dae' ),
        array( 'model/vnd.dwf' => 'dwf' ),
        array( 'model/vnd.gdl' => 'gdl' ),
        array( 'model/vnd.gtw' => 'gtw' ),
        array( 'model/vnd.mts' => 'mts' ),
        array( 'model/vnd.vtu' => 'vtu' ),
        array( 'model/vrml' => 'wrl' ),
        array( 'model/x3d+binary' => 'x3db' ),
        array( 'model/x3d+vrml' => 'x3dv' ),
        array( 'model/x3d+xml' => 'x3d' ),
        array( 'text/cache-manifest' => 'appcache' ),
        array( 'text/calendar' => 'ics' ),
        array( 'text/css' => 'css' ),
        array( 'text/csv' => 'csv' ),
        array( 'text/html' => 'html' ),
        array( 'text/n3' => 'n3' ),
        array( 'text/plain' => 'txt' ),
        array( 'text/prs.lines.tag' => 'dsc' ),
        array( 'text/richtext' => 'rtx' ),
        array( 'text/rtf' => 'rtf' ),
        array( 'text/sgml' => 'sgml' ),
        array( 'text/tab-separated-values' => 'tsv' ),
        array( 'text/troff' => 't' ),
        array( 'text/turtle' => 'ttl' ),
        array( 'text/uri-list' => 'uri' ),
        array( 'text/vcard' => 'vcard' ),
        array( 'text/vnd.curl' => 'curl' ),
        array( 'text/vnd.curl.dcurl' => 'dcurl' ),
        array( 'text/vnd.curl.scurl' => 'scurl' ),
        array( 'text/vnd.curl.mcurl' => 'mcurl' ),
        array( 'text/vnd.dvb.subtitle' => 'sub' ),
        array( 'text/vnd.fly' => 'fly' ),
        array( 'text/vnd.fmi.flexstor' => 'flx' ),
        array( 'text/vnd.graphviz' => 'gv' ),
        array( 'text/vnd.in3d.3dml' => '3dml' ),
        array( 'text/vnd.in3d.spot' => 'spot' ),
        array( 'text/vnd.sun.j2me.app-descriptor' => 'jad' ),
        array( 'text/vnd.wap.wml' => 'wml' ),
        array( 'text/vnd.wap.wmlscript' => 'wmls' ),
        array( 'text/x-asm' => 's' ),
        array( 'text/x-c' => 'c' ),
        array( 'text/x-fortran' => 'f' ),
        array( 'text/x-pascal' => 'p' ),
        array( 'text/x-java-source' => 'java' ),
        array( 'text/x-opml' => 'opml' ),
        array( 'text/x-nfo' => 'nfo' ),
        array( 'text/x-setext' => 'etx' ),
        array( 'text/x-sfv' => 'sfv' ),
        array( 'text/x-uuencode' => 'uu' ),
        array( 'text/x-vcalendar' => 'vcs' ),
        array( 'text/x-vcard' => 'vcf' ),
        array( 'video/3gpp' => '3gp' ),
        array( 'video/3gpp2' => '3g2' ),
        array( 'video/h261' => 'h261' ),
        array( 'video/h263' => 'h263' ),
        array( 'video/h264' => 'h264' ),
        array( 'video/jpeg' => 'jpgv' ),
        array( 'video/jpm' => 'jpm' ),
        array( 'video/mj2' => 'mj2' ),
        array( 'video/mp4' => 'mp4' ),
        array( 'video/mpeg' => 'mpeg' ),
        array( 'video/ogg' => 'ogv' ),
        array( 'video/quicktime' => 'qt' ),
        array( 'video/vnd.dece.hd' => 'uvh' ),
        array( 'video/vnd.dece.mobile' => 'uvm' ),
        array( 'video/vnd.dece.pd' => 'uvp' ),
        array( 'video/vnd.dece.sd' => 'uvs' ),
        array( 'video/vnd.dece.video' => 'uvv' ),
        array( 'video/vnd.dvb.file' => 'dvb' ),
        array( 'video/vnd.fvt' => 'fvt' ),
        array( 'video/vnd.mpegurl' => 'mxu' ),
        array( 'video/vnd.ms-playready.media.pyv' => 'pyv' ),
        array( 'video/vnd.uvvu.mp4' => 'uvu' ),
        array( 'video/vnd.vivo' => 'viv' ),
        array( 'video/webm' => 'webm' ),
        array( 'video/x-f4v' => 'f4v' ),
        array( 'video/x-fli' => 'fli' ),
        array( 'video/x-flv' => 'flv' ),
        array( 'video/x-m4v' => 'm4v' ),
        array( 'video/x-matroska' => 'mkv' ),
        array( 'video/x-mng' => 'mng' ),
        array( 'video/x-ms-asf' => 'asf' ),
        array( 'video/x-ms-vob' => 'vob' ),
        array( 'video/x-ms-wm' => 'wm' ),
        array( 'video/x-ms-wmv' => 'wmv' ),
        array( 'video/x-ms-wmx' => 'wmx' ),
        array( 'video/x-ms-wvx' => 'wvx' ),
        array( 'video/x-msvideo' => 'avi' ),
        array( 'video/x-sgi-movie' => 'movie' ),
        array( 'video/x-smv' => 'smv' ),
        array( 'x-conference/x-cooltalk' => 'ice' ),
    );

    /**
     * BC : Custom mime types added because they were missing from symfony defaults list of mimetypes
     */
    protected $customMimeTypeExtensions = array(
        array( 'application/x-gzip' => 'tar.gz' ),
        array( 'application/x-gtar' => 'tar.bz2' ),
        array( 'application/x-gzip' => 'tgz' ),
        array( 'application/x-gzip' => 'gz' ),
        array( 'audio/ogg' => 'ogg' ),
    );

    /**
     * Constructor
     */
    public function __construct()
    {
        $this->defaultExtensions = array_merge( $this->defaultExtensions, $this->customMimeTypeExtensions );
    }

    /**
     * Search for item in array and return resulting containing array
     *
     * @param string $needle Text to find
     * @param array $haystack Array of content to search within
     * @param bool $strict Wheather to perform strict matching. Unused
     * @return bool
     */
    public function findMimeTypeByExtension( $needle, $haystack, $strict = true )
    {
        $found = false;

        foreach ( $haystack as $key => $item )
        {
            if ( $item == $needle )
            {
                $found = array( $item, $key );
                break;
            }
            else if ( is_array( $item ) )
            {
                $found = $this->findMimeTypeByExtension( $needle, $item, $strict );
                if ( is_array( $found ) )
                {
                    break;
                }
            }
        }

        return $found;
    }

    /**
     * Tries to guess the file mimetype based on file extension.
     *
     * @param string $fileNameExtension The file extension
     * @return array The guessed mimetype or false, if none could be guessed
     */
    public function guess( $fileNameExtension )
    {
        $guess = $this->findMimeTypeByExtension( strtolower( $fileNameExtension ), $this->defaultExtensions );

        return $guess;
    }

    /**
     * Tries to guess the file mimetype based on file extension.
     *
     * @param string $url The file url
     * @return array The guessed mimetype or false, if none could be guessed
     */
    public function guessByUrl( $url )
    {
        $urlFileName = basename( $url );
        $urlFileNameArray = explode( '.', $urlFileName );
        $urlFileNameExtension = $urlFileNameArray[1];

        return $this->guess( $urlFileNameExtension );
    }
}
